export const NOTIFICATIONS_REPOSITORY = Symbol('NOTIFICATIONS_REPOSITORY');
export const NOTIFICATIONS_PRESENCE_CHECKER = Symbol('NOTIFICATIONS_PRESENCE_CHECKER');
export const PUSH_PROVIDER = Symbol('PUSH_PROVIDER');
